# Generated by Django 5.2.6 on 2025-09-11 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(null=True, verbose_name='Год начала')),
                ('start_month', models.PositiveIntegerField(null=True, verbose_name='Месяц начала')),
                ('start_day', models.PositiveIntegerField(null=True, verbose_name='День начала')),
                ('calendar_start', models.IntegerField(choices=[(1, 'Григорианский календарь'), (2, 'Юлианский календарь')], default=1, verbose_name='Календарь даты начала')),
                ('end_year', models.IntegerField(null=True, verbose_name='Год окончания')),
                ('end_month', models.PositiveIntegerField(null=True, verbose_name='Месяц окончания')),
                ('end_day', models.PositiveIntegerField(null=True, verbose_name='День окончания')),
                ('calendar_end', models.IntegerField(choices=[(1, 'Григорианский календарь'), (2, 'Юлианский календарь')], default=1, verbose_name='Календарь даты окончания')),
                ('type', models.IntegerField(choices=[(1, 'Государство'), (2, 'Промежуточная часть'), (3, 'Населённый пункт')], verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Административно-территориальная единица',
                'verbose_name_plural': 'Административно-территориальные единицы',
            },
        ),
        migrations.CreateModel(
            name='Including',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(null=True, verbose_name='Год начала')),
                ('start_month', models.PositiveIntegerField(null=True, verbose_name='Месяц начала')),
                ('start_day', models.PositiveIntegerField(null=True, verbose_name='День начала')),
                ('calendar_start', models.IntegerField(choices=[(1, 'Григорианский календарь'), (2, 'Юлианский календарь')], default=1, verbose_name='Календарь даты начала')),
                ('end_year', models.IntegerField(null=True, verbose_name='Год окончания')),
                ('end_month', models.PositiveIntegerField(null=True, verbose_name='Месяц окончания')),
                ('end_day', models.PositiveIntegerField(null=True, verbose_name='День окончания')),
                ('calendar_end', models.IntegerField(choices=[(1, 'Григорианский календарь'), (2, 'Юлианский календарь')], default=1, verbose_name='Календарь даты окончания')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_includings', to='adminunits.unit', verbose_name='АТЕ')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_includings', to='adminunits.unit', verbose_name='АТЕ уровнем выше')),
            ],
            options={
                'verbose_name': 'Включение',
                'verbose_name_plural': 'Включения',
            },
        ),
        migrations.CreateModel(
            name='UnitName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(null=True, verbose_name='Год начала')),
                ('start_month', models.PositiveIntegerField(null=True, verbose_name='Месяц начала')),
                ('start_day', models.PositiveIntegerField(null=True, verbose_name='День начала')),
                ('calendar_start', models.IntegerField(choices=[(1, 'Григорианский календарь'), (2, 'Юлианский календарь')], default=1, verbose_name='Календарь даты начала')),
                ('end_year', models.IntegerField(null=True, verbose_name='Год окончания')),
                ('end_month', models.PositiveIntegerField(null=True, verbose_name='Месяц окончания')),
                ('end_day', models.PositiveIntegerField(null=True, verbose_name='День окончания')),
                ('calendar_end', models.IntegerField(choices=[(1, 'Григорианский календарь'), (2, 'Юлианский календарь')], default=1, verbose_name='Календарь даты окончания')),
                ('name', models.CharField(max_length=200, verbose_name='Название АТЕ')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='adminunits.unit', verbose_name='АТЕ')),
            ],
            options={
                'verbose_name': 'Наименование',
                'verbose_name_plural': 'Наименования',
            },
        ),
    ]
