# Generated by Django 5.2.6 on 2025-09-16 11:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminunits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='including',
            options={'verbose_name': 'Вхождение', 'verbose_name_plural': 'Вхождения'},
        ),
        migrations.AlterModelOptions(
            name='unitname',
            options={'verbose_name': 'Наименование АТЕ', 'verbose_name_plural': 'Наименования АТЕ'},
        ),
        migrations.AddField(
            model_name='unit',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='Позиция на карте'),
        ),
        migrations.AlterField(
            model_name='unitname',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование АТЕ'),
        ),
    ]
